accounts/urls.py
from django.urls import path, include
from django.contrib.auth.views import (
    LoginView, LogoutView, PasswordChangeView,
    PasswordChangeDoneView, PasswordResetView,
    PasswordResetDoneView, PasswordResetConfirmView,
    PasswordResetCompleteView
)
from django.urls import reverse_lazy

from .views import SignUpView

app_name = 'accounts'

urlpatterns = [
    # Login
    path(
        'login/',
        LoginView.as_view(
            template_name='accounts/login.html'
        ),
        name='login'
    ),

    # Logout
    path(
        'logout/',
        LogoutView.as_view(),
        name='logout'
    ),

    # Password change
    path(
        'password_change/done/',
        PasswordChangeDoneView.as_view(
            template_name='accounts/password_changed.html'
        ),
        name='password_change_done'
    ),
    path(
        'password_change/',
        PasswordChangeView.as_view(
            template_name='accounts/password_change.html',
            success_url=reverse_lazy(
                'accounts:password_change_done'
            )
        ),
        name='password_change'
    ),

    # Password reset
    path(
        'password_reset/',
        PasswordResetView.as_view(
            template_name='accounts/password_reset/'
                'password_reset.html',
            subject_template_name='accounts/password_reset/'
                'email_subject.txt',
            email_template_name='accounts/password_reset/'
                'email_message.html',
            success_url=reverse_lazy(
                'accounts:password_reset_done'
            )
        ),
        name='password_reset'
    ),
    path(
        'password_reset/done/',
        PasswordResetDoneView.as_view(
            template_name='accounts/password_reset/'
                'email_sent.html'
        ),
        name='password_reset_done'
    ),
    path(
        'password_reset_confirm/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(
            template_name='accounts/password_reset/'
                'password_reset_confirm.html',
            success_url=reverse_lazy(
                'accounts:password_reset_complete'
            )
        ),
        name='password_reset_confirm'
    ),
    path(
        'password_reset_complete',
        PasswordResetCompleteView.as_view(
            template_name='accounts/password_reset/'
            'password_reset_complete.html'
        ),
        name='password_reset_complete'
    ),

    # Sign up
    path(
        'sign_up/',
        SignUpView.as_view(),
        name='sign_up'
    ),
]

books/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from .views import (
    BookListView, BookDetailView, AuthorListView,
    PublishingHouseView, EpisodeView, GenreView,
    SearchBookAndAuthorView
)


app_name = 'books'

urlpatterns = [
    # Index page with all books
    path('', BookListView.as_view(), name='index'),

    # Book detail info
    path(
        'book/<int:pk>/',
        cache_page(60 * 30)(BookDetailView.as_view()),
        name='book_detail_info'
    ),

    # Author info
    path(
        'author/<int:author_id>/',
        cache_page(60 * 30)(AuthorListView.as_view()),
        name='author_info'
    ),

    # Publishing house info
    path(
        'publishing_house/<int:publ_id>/',
        cache_page(60 * 30)(PublishingHouseView.as_view()),
        name='publishing_house_info'
    ),
    
    # Episode's books
    path(
        'episode/<int:episode_id>/',
        cache_page(60 * 30)(EpisodeView.as_view()),
        name='episode_books'
    ),

    # Genre's books
    path(
        'genre/<int:genre_id>/',
        cache_page(60 * 30)(GenreView.as_view()),
        name='genre_books'
    ),

    # Search book and author
    path(
        'search/',
        SearchBookAndAuthorView.as_view(),
        name='search'
    ),
]

labirint_ru_v2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

import debug_toolbar

urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/', include('books.urls')),
    path('accounts/', include('accounts.urls')),

    # For VK login
    path(
        'social/',
        include('social_django.urls', namespace='social'),
    ),

    # Debug toolbar
    path(
        '__debug__/',
        include(debug_toolbar.urls),
    ),

    # Simple captcha
    path(
        'captcha/',
        include('captcha.urls')
    )
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

accounts/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from captcha.fields import CaptchaField


class RegistrationForm(UserCreationForm):
    email = forms.EmailField()
    captcha = CaptchaField()

    class Meta:
        fields = (
            'username', 'email',
            'password1', 'password2',
            'captcha',
        )
        model = User

accounts/views.py
from django.views.generic.edit import CreateView
from django.urls import reverse_lazy

from .forms import RegistrationForm


class SignUpView(CreateView):
    form_class = RegistrationForm
    template_name = 'accounts/sign_up.html'
    success_url = reverse_lazy('accounts:login')

templates/accounts/login.html
{% extends 'layouts/default_form.html' %}

{% load static %}

{% block title %}Вход на сайт | Лабиринт{% endblock title %}
    
{% block form_button %}
    <input class='btn btn-primary' type="submit" value="Войти">
{% endblock form_button %}

{% block after_form %}
    <p>
        <a class='text-dark'
        href="{% url 'accounts:password_reset' %}">
            Забыли пароль?
        </a>
    </p>
    
    <p>
        <a class='text-dark'
        href="{% url 'accounts:sign_up' %}">
            <input class='btn btn-success' type="submit" value="Регистрация">
        </a>
    </p>

    <p>
        <a class='text-dark'
        href="{% url 'social:begin' 'vk-oauth2' %}">
            <img src="{% static 'accounts/img/vk.png' %}"
            alt="VK" height="50">
        </a>
    </p>
{% endblock after_form %}

templates/accounts/password_change.html
{% extends 'layouts/default_form.html' %}

{% block title %}
    {{ user.username }} | Смена пароля | Лабиринт
{% endblock title %}

{% block form_button %}
    <input class='btn btn-success' type="submit" value="Сохранить">
{% endblock form_button %}

templates/accounts/password_changed.html
{% extends 'layouts/implemented.html' %}

{% block title %}
    {{ user.username }} | Пароль изменен | 
{% endblock title %}    

{% block text %}
    <h1>Пароль изменен</h1>    
{% endblock text %}
    

templates/accounts/sign_up.html
{% extends 'layouts/default_form.html' %}

{% block title %}
{{ user.username }} | Регистрация | Лабиринт
{% endblock title %}

{% block form_button %}
<input class='btn btn-success'
type="submit" value="Зарегестрироваться">
{% endblock form_button %}