books/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from .views import (
    BookListView, BookDetailView, AuthorListView,
    PublishingHouseView, EpisodeView, GenreView,
    SearchBookAndAuthorView
)


app_name = 'books'

urlpatterns = [
    # Index page with all books
    path('', BookListView.as_view(), name='index'),

    # Book detail info
    path(
        'book/<int:pk>/',
        cache_page(60 * 30)(BookDetailView.as_view()),
        name='book_detail_info'
    ),

    # Author info
    path(
        'author/<int:author_id>/',
        cache_page(60 * 30)(AuthorListView.as_view()),
        name='author_info'
    ),

    # Publishing house info
    path(
        'publishing_house/<int:publ_id>/',
        cache_page(60 * 30)(PublishingHouseView.as_view()),
        name='publishing_house_info'
    ),
    
    # Episode's books
    path(
        'episode/<int:episode_id>/',
        cache_page(60 * 30)(EpisodeView.as_view()),
        name='episode_books'
    ),

    # Genre's books
    path(
        'genre/<int:genre_id>/',
        cache_page(60 * 30)(GenreView.as_view()),
        name='genre_books'
    ),

    # Search book and author
    path(
        'search/',
        SearchBookAndAuthorView.as_view(),
        name='search'
    ),
]

labirint_ru_v2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

import debug_toolbar

urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/', include('books.urls')),
    path('accounts/', include('accounts.urls')),

    # For VK login
    path(
        'social/',
        include('social_django.urls', namespace='social'),
    ),

    # Debug toolbar
    path(
        '__debug__/',
        include(debug_toolbar.urls),
    ),

    # Simple captcha
    path(
        'captcha/',
        include('captcha.urls')
    )
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

books/models.py
from django.db import models


COVER_TYPES = (
    ('solid', '7Б - твердая (плотная бумага или картон)'),
    ('soft', 'мягкий переплет (крепление скрепкой или клеем)'),
    ('with_flaps', 'Обл. с клапанами'),
)
ILLUSTRATIONS_INFO = (
    ('bw', 'Черно-белые'),
    ('color', 'Цветные'),
    ('none', 'Без иллюстраций'),
)


class Author(models.Model):
    """Book author"""

    # Used for book description
    name = models.CharField(
        'Имя автора',
        help_text='Имя автора, указываемое в описании книги',
        max_length=100,
        unique=True,
    )

    # Used for author description
    full_name = models.CharField(
        'Полное имя автора',
        max_length=100,
        unique=True,
    )
    info = models.TextField(
        'Информация об авторе',
        null=True,
        blank=True,
    )
    image = models.ImageField(
        'Фотография автора',
        unique=True,
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Автор'
        verbose_name_plural = 'Авторы'
        ordering = ['name']
        db_table = 'author'


class PublishingHouse(models.Model):
    """Book publishing house"""

    name = models.CharField(
        'Название издательства',
        max_length=100,
        unique=True,
    )
    info = models.TextField(
        'Информация об издательстве',
        null=True,
        blank=True,
    )
    image = models.ImageField(
        verbose_name='Логотип издательства',
        unique=True,
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Издательство'
        verbose_name_plural = 'Издательства'
        ordering = ['name']
        db_table = 'publishing_house'


class Episode(models.Model):
    """Publishing house episode"""
    name = models.CharField(
        'Название серии',
        max_length=100,
        unique=True,
    )
    publishing_house = models.ForeignKey(
        'PublishingHouse',
        on_delete=models.CASCADE,
        verbose_name='Издательство серии',
        related_name='episodes'
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Серия'
        verbose_name_plural = 'Серии'
        ordering = ['name']
        db_table = 'episode'


class Genre(models.Model):
    """Book genre"""

    name = models.CharField(
        'Название жанра',
        max_length=100,
        unique=True
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Жанр'
        verbose_name_plural = 'Жанры'
        ordering = ['name']
        db_table = 'genre'


class Book(models.Model):
    """Book"""

    title = models.CharField(
        'Название книги',
        max_length=255
    )
    authors = models.ManyToManyField(
        'Author',
        verbose_name='Автор(ы) книги',
    )
    publishing_house = models.ForeignKey(
        'PublishingHouse',
        on_delete=models.CASCADE,
        verbose_name='Книжное издательство',
    )
    episode = models.ForeignKey(
        'Episode',
        on_delete=models.CASCADE,
        verbose_name='Серия книжного издательства',
        null=True,
        blank=True,
    )

    price = models.PositiveIntegerField('Цена книги')

    genres = models.ManyToManyField(
        'Genre',
        verbose_name='Жанр книги',
        blank=True
    )

    ID = models.PositiveIntegerField('ID книги')

    ISBN = models.CharField('ISBN книги', max_length=30)

    pages_amount = models.PositiveIntegerField(
        'Количество страниц в книге'
    )

    weight = models.PositiveIntegerField('Масса книги (г)')

    sizes = models.CharField('Размеры книги', max_length=20)

    cover_type = models.CharField(
        'Тип обложки книги',
        max_length=50,
        choices=COVER_TYPES,
        default='solid'
    )
    illustrations_info = models.CharField(
        'Информация об иллюстрации',
        max_length=50,
        choices=ILLUSTRATIONS_INFO,
        default='none'
    )
    annotation = models.TextField(
        'Аннотация к книге',
        null=True,
        blank=True
    )
    published_date = models.DateField(
        'Дата публикации книги',
        auto_now_add=True
    )
    image = models.ImageField(
        'Изображение обложки книги',
    )

    # To display the authors of the book on the administrative site
    def get_authors(self):
        return '\n'.join(
            [author.name for author in self.authors.all()]
        )
    
    # To display the genres of the book on the administrative site
    def get_genres(self):
        return '\n'.join(
            [genre.name for genre in self.genres.all()]
        )

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Книга'
        verbose_name_plural = 'Книги'
        ordering = ['published_date', 'title']
        db_table = 'book'

books/views.py
from django.views.generic.list import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.detail import DetailView
from django.db.models import Q

from .models import (
    Book, Author, Episode,
    PublishingHouse, Genre
)


class BookListView(LoginRequiredMixin, ListView):
    """Class with all books which used on index page"""
    
    template_name = 'books/index.html'
    paginate_by = 8
    context_object_name = 'books'
    queryset = Book.objects.prefetch_related(
        'authors', 'publishing_house', 'episode',
    )


class BookDetailView(LoginRequiredMixin, DetailView):
    """Class with book detail info"""

    model = Book
    template_name = 'books/book_detail.html'


class TemplateView(LoginRequiredMixin, ListView):
    """
    Template view for author, genre,
    publishing_house and episode view
    
    """

    paginate_by = 8
    context_object_name = 'books'        

    def get_prefetch_related_queryset(self):
        return Book.objects.prefetch_related(
            'authors', 'genres',
            'publishing_house', 'episode'
        )


class AuthorListView(TemplateView):
    """Author info view"""

    template_name = 'books/author_info.html'

    def get_queryset(self):
        return super().get_prefetch_related_queryset().filter(
            authors=self.kwargs['author_id']
        )

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['author'] = Author.objects.get(
            pk=self.kwargs['author_id']
        )

        return context


class PublishingHouseView(TemplateView):
    """Publishing house info view"""

    template_name = 'books/publishing_house_info.html'

    def get_queryset(self):
        return super().get_prefetch_related_queryset().filter(
            publishing_house=self.kwargs['publ_id']
        )

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['publ_house'] = PublishingHouse.objects.get(
            pk=self.kwargs['publ_id']
        )
        context['episodes'] = context['publ_house'].episodes.all()

        return context


class EpisodeView(TemplateView):
    """Episode's books view"""

    template_name = 'books/episode_books.html'

    def get_queryset(self):
        return super().get_prefetch_related_queryset().filter(
            episode=self.kwargs['episode_id']
        )

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['episode'] = Episode.objects.get(
            pk=self.kwargs['episode_id']
        )

        return context


class GenreView(TemplateView):
    """Genre's books view"""

    template_name = 'books/genre_books.html'

    def get_queryset(self):
        return super().get_prefetch_related_queryset().filter(
            genres=self.kwargs['genre_id']
        )

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['genre'] = Genre.objects.get(
            pk=self.kwargs['genre_id']
        )

        return context


class SearchBookAndAuthorView(ListView):
    model = Book
    template_name = 'books/search_book_and_author.html'
    context_object_name = 'books'

    def get_queryset(self):
        query = self.request.GET.get('q')

        return Book.objects.filter(
            Q(title__icontains=query) | Q(authors__name__icontains=query)
        )

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['query'] = self.request.GET.get('q')

        return context

templates/books/author_info.html
{% extends 'layouts/print_books.html' %}

{% load static %}

{% block title %}
Книги автора {{ author }} | Лабиринт
{% endblock title %}

{% block main_text %}
<!-- Authors full names -->
<div class="row">
    <div class="col-md-6 offset-md-1">
        <h2>{{ author.full_name }}</h2>
    </div>
</div>

<hr>

<!-- Authors info -->
<div class="row">
    <div class="col-md-6 offset-md-1">
        <h4>{{ author.info }}</h4>
    </div>

    <div class="col-md-2 offset-md-1">
        <img src="{{ author.image.url }}" alt="{{ author }}" height="160">
    </div>
</div>

<hr>
{% endblock main_text %}

templates/books/book_detail.html
{% extends 'layouts/basic.html' %}

{% block title %}
Книга: {{ book }} ({{ book.get_authors }})
{% endblock title %}

{% block content %}
<div class="row">
    <!-- Top title -->
    <div class="col-md-4 offset-md-3">
        <h4>
            {{book.get_authors}}: {{book}}
        </h4>
    </div>

    <!-- Description -->
    <div class="jumbotron col-md-4 offset-md-3">
        <div class="row">
            <!-- Image -->
            <div class="col-md-2">
                <img src="{{ book.image.url }}" alt="{{ book }}" height="340">
            </div>

            <!-- Description without image -->
            <div class="col-md-5 offset-md-4">
                <div>
                    <!-- Author -->
                    {% for author in book.authors.all %}
                    <h6>Автор:
                        <a class='text-dark' href="{% url 'books:author_info' author.pk %}">
                            {{ author }}
                        </a>
                    </h6>
                    {% endfor %}

                    <!-- Publishing house -->
                    <h6>Издательство:
                        <a class='text-dark' href="{% url 'books:publishing_house_info' book.publishing_house.pk %}">
                            {{ book.publishing_house }}
                        </a>
                    </h6>

                    <!-- Episode -->
                    {% if book.episode %}
                    <h6>Серия:
                        <a class='text-dark' href="{% url 'books:episode_books' book.episode.pk %}">
                            {{ book.episode }}
                        </a>
                    </h6>
                    {% endif %}

                    <!-- Genres -->
                    {% if book.get_genres %}
                    {% for genre in book.genres.all %}
                    <h6>Жанр:
                        <a class='text-dark' href="{% url 'books:genre_books' genre.pk %}">
                            {{ genre }}
                        </a>
                    </h6>
                    {% endfor %}
                    {% endif %}

                    <hr>

                    <!-- Price -->
                    <h6>Ваша цена:</h6>
                    <h5>{{ book.price }} р.</h5>

                    <hr>

                    <h6>ID товара: {{ book.ID }}</h6>
                    <h6>ISBN: {{ book.ISBN }}</h6>
                    <h6>Страниц: {{ book.pages_amount }}</h6>
                    <h6>Масса: {{ book.weight }} г</h6>
                    <h6>Размеры: {{ book.sizes }} мм</h6>
                </div>
            </div>
        </div>
    </div>

    <!-- Annotation -->
    <div class="col-md-4">
        <h6><b>Аннотация к книге "{{ book }}"</b></h6>
        <h6>{{ book.annotation }}</h6>
    </div>
</div>
{% endblock content %}

templates/books/episode_books.html
{% extends 'layouts/print_books.html' %}

{% block title %}
Книги серии {{ episode }}
{% endblock title %}

{% block main_text %}
<div class="row">
    <div class="col-md-6 offset-md-1">
        <h2>Издательство 
            <a class='text-dark'
            href="{% url 'books:publishing_house_info' episode.publishing_house.pk %}">
                «{{ episode.publishing_house }}»
            </a>
        </h2>
        <h2>Серия «{{ episode }}»</h2>
    </div>
</div>

<hr>

<div class="row">
    <div class="col-md-6 offset-md-1">
        <h4>{{ episode.publishing_house.info }}</h4>
    </div>
</div>

<hr>
{% endblock main_text %}

templates/books/genre_books.html
{% extends 'layouts/print_books.html' %}

{% block title %}
Книги жанра {{ genre }}
{% endblock title %}

{% block main_text %}
<div class="row">
    <div class="col-md-6 offset-md-1">
        <h2>Жанр «{{ genre }}»</h2>
    </div>
</div>

<hr>
{% endblock main_text %}

templates/books/index.html
{% extends 'layouts/print_books.html' %}

{% block title %}Главная - Лабиринт{% endblock title %}

hello

templates/books/publishing_house_info.html
{% extends 'layouts/print_books.html' %}

{% load static %}

{% block title %}
Издательство {{ publ_house }}
{% endblock title %}

{% block main_text %}
<!-- Publishing house name -->
<div class="row">
    <div class="col-md-6 offset-md-1">
        <h2>Издательство «{{ publ_house }}»</h2>
    </div>
</div>

<hr>

<!-- Publishing house info -->
<div class="row">
    <div class="col-md-6 offset-md-1">
        <h4><b>Об издательстве</b></h4>
        <h4>{{ publ_house.info }}</h4>
    </div>

    <div class="col-md-2 offset-md-1">
        <img src="{{ publ_house.image.url }}" alt="{{ publ_house }}" height="160">
    </div>
</div>

<hr>

<!-- Publishing house series -->
<div class="row">
    <div class="col-md-6 offset-md-1">
        <h4><b>Серии</b></h4>
        {% for episode in episodes %}
            <h4>
                <a class='text-dark' href="{% url 'books:episode_books' episode.pk %}">
                    {{ episode }}
                </a>
            </h4>
        {% endfor %}
    </div>
</div>

<hr>
{% endblock main_text %}

templates/books/search_book_and_author.html
{% extends 'layouts/print_books.html' %}

{% block title %}
Результаты по запросу "{{ query }}"
{% endblock title %}