accounts/urls.py
from django.urls import path, include
from django.contrib.auth.views import (
    LoginView, LogoutView, PasswordChangeView,
    PasswordChangeDoneView, PasswordResetView,
    PasswordResetDoneView, PasswordResetConfirmView,
    PasswordResetCompleteView
)
from django.urls import reverse_lazy

from .views import SignUpView

app_name = 'accounts'

urlpatterns = [
    # Login
    path(
        'login/',
        LoginView.as_view(
            template_name='accounts/login.html'
        ),
        name='login'
    ),

    # Logout
    path(
        'logout/',
        LogoutView.as_view(),
        name='logout'
    ),

    # Password change
    path(
        'password_change/done/',
        PasswordChangeDoneView.as_view(
            template_name='accounts/password_changed.html'
        ),
        name='password_change_done'
    ),
    path(
        'password_change/',
        PasswordChangeView.as_view(
            template_name='accounts/password_change.html',
            success_url=reverse_lazy(
                'accounts:password_change_done'
            )
        ),
        name='password_change'
    ),

    # Password reset
    path(
        'password_reset/',
        PasswordResetView.as_view(
            template_name='accounts/password_reset/'
                'password_reset.html',
            subject_template_name='accounts/password_reset/'
                'email_subject.txt',
            email_template_name='accounts/password_reset/'
                'email_message.html',
            success_url=reverse_lazy(
                'accounts:password_reset_done'
            )
        ),
        name='password_reset'
    ),
    path(
        'password_reset/done/',
        PasswordResetDoneView.as_view(
            template_name='accounts/password_reset/'
                'email_sent.html'
        ),
        name='password_reset_done'
    ),
    path(
        'password_reset_confirm/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(
            template_name='accounts/password_reset/'
                'password_reset_confirm.html',
            success_url=reverse_lazy(
                'accounts:password_reset_complete'
            )
        ),
        name='password_reset_confirm'
    ),
    path(
        'password_reset_complete',
        PasswordResetCompleteView.as_view(
            template_name='accounts/password_reset/'
            'password_reset_complete.html'
        ),
        name='password_reset_complete'
    ),

    # Sign up
    path(
        'sign_up/',
        SignUpView.as_view(),
        name='sign_up'
    ),
]

books/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from .views import (
    BookListView, BookDetailView, AuthorListView,
    PublishingHouseView, EpisodeView, GenreView,
    SearchBookAndAuthorView
)


app_name = 'books'

urlpatterns = [
    # Index page with all books
    path('', BookListView.as_view(), name='index'),

    # Book detail info
    path(
        'book/<int:pk>/',
        cache_page(60 * 30)(BookDetailView.as_view()),
        name='book_detail_info'
    ),

    # Author info
    path(
        'author/<int:author_id>/',
        cache_page(60 * 30)(AuthorListView.as_view()),
        name='author_info'
    ),

    # Publishing house info
    path(
        'publishing_house/<int:publ_id>/',
        cache_page(60 * 30)(PublishingHouseView.as_view()),
        name='publishing_house_info'
    ),
    
    # Episode's books
    path(
        'episode/<int:episode_id>/',
        cache_page(60 * 30)(EpisodeView.as_view()),
        name='episode_books'
    ),

    # Genre's books
    path(
        'genre/<int:genre_id>/',
        cache_page(60 * 30)(GenreView.as_view()),
        name='genre_books'
    ),

    # Search book and author
    path(
        'search/',
        SearchBookAndAuthorView.as_view(),
        name='search'
    ),
]

labirint_ru_v2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

import debug_toolbar

urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/', include('books.urls')),
    path('accounts/', include('accounts.urls')),

    # For VK login
    path(
        'social/',
        include('social_django.urls', namespace='social'),
    ),

    # Debug toolbar
    path(
        '__debug__/',
        include(debug_toolbar.urls),
    ),

    # Simple captcha
    path(
        'captcha/',
        include('captcha.urls')
    )
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

templates/basic.html
{% load static %}
{% load cache %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <!-- Load Bootstrap -->
        <link rel='stylesheet'
            href='https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css'
        integrity='sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2'
        crossorigin='anonymous'>
        
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
            integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
        
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
        crossorigin="anonymous"></script>

        <link rel="shortcut icon" type="image/png" href="{% static 'books/img/favicon.ico' %}" />

        <title>{% block title %}{% endblock title %}</title>
    </head>
    <body>
        <!-- Navbar -->
        <nav class='navbar navbar-expand-lg navbar-dark bg-dark'>
            {% cache 60 * 30 cache_navbar_brand %}            
            <a class='navbar-brand' href='{% url 'books:index' %}'>
                <img src='{% static "books/img/labirint.jpg" %}' width='30' height='30'>
                Лабиринт
            </a>
            {% endcache %}

            <div class='collapse navbar-collapse'>
                <div class='navbar-nav'>
                    <li class="nav-item dropdown">
                        {% if user.is_authenticated %}
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown"
                            aria-haspopup="true" aria-expanded="false">
                            {{ user.username }}
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            {% if user.is_authenticated %}
                            <a class='dropdown-item' href='{% url "accounts:logout" %}'>
                                Выйти
                            </a>
        
                            <a class='dropdown-item' href='{% url "accounts:password_change" %}'>
                                Сменить пароль
                            </a>
                            {% endif %}
                        </div>
                        {% endif %}
                    </li>
                    <a class='nav-link' href='#'>
                    </a>
                </div>
            </div>
            
            <form class="form-inline" method="get" action="{% url 'books:search' %}">
                <input name="q" type="search" class="form-control mr-sm-2" placeholder="Поиск по Лабиринту" aria-label="Search">
        
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">
                    Искать
                </button>
            </form>
        </nav>

        <section>
            {% block content %}
            {% endblock content %}
        </section>
        
        <!-- Pagination -->
        <footer>
            <br><br>
            <!-- Next and previous -->
            {% if page_obj.has_next and page_obj.has_previous %}
            <ul class='pagination justify-content-center'>
                <li class="page-item">
                    <a class="page-link"
                    href="?page={{ page_obj.previous_page_number }}">
                        Previous
                    </a>
                </li>
        
                <li class='page-item'>
                    <a class='page-link btn btn-outline-primary'
                    href="?page={{ page_obj.previous_page_number }}">
                        {{ page_obj.previous_page_number }}
                    </a>
                </li>
        
                <li class='page-item'>
                    <a class='page-link btn btn-outline-primary active'
                    href="?page={{ page_obj.number }}">
                        {{ page_obj.number }}
                    </a>
                </li>
        
                <li class='page-item'>
                    <a class='page-link btn btn-outline-primary'
                    href="?page={{ page_obj.next_page_number }}">
                        {{ page_obj.next_page_number }}
                    </a>
                </li>
        
                <li class="page-item">
                    <a class="page-link"
                    href="?page={{ page_obj.next_page_number }}">Next</a>
                </li>
            </ul>
        
            <!-- Only next -->
            {% elif page_obj.has_next %}
            <ul class="pagination justify-content-center">
                <li class="page-item disabled">
                    <a class="page-link" href="#">Previous</a>
                </li>
    
                <li class='page-item'>
                    <a class='page-link btn btn-outline-primary active' href="?page={{ page_obj.number }}">
                        {{ page_obj.number }}
                    </a>
                </li>
    
                <li class='page-item'>
                    <a class='page-link btn btn-outline-primary' href="?page={{ page_obj.next_page_number }}">
                        {{ page_obj.next_page_number }}
                    </a>
                </li>
    
                <li class="page-item">
                    <a class="page-link"
                    href="?page={{ page_obj.next_page_number }}">Next</a>
                </li>
            </ul>
        
            <!-- Only previous -->
            {% elif page_obj.has_previous %}
            <ul class='pagination justify-content-center'>
                <li class="page-item">
                    <a class="page-link"
                    href="?page={{ page_obj.previous_page_number }}">Previous</a>
                </li>
        
                <li class='page-item'>
                    <a class='page-link btn btn-outline-primary' href="?page={{ page_obj.previous_page_number }}">
                        {{ page_obj.previous_page_number }}
                    </a>
                </li>
        
                <li class='page-item'>
                    <a class='page-link btn btn-outline-primary active' href="?page={{ page_obj.number }}">
                        {{ page_obj.number }}
                    </a>
                </li>
        
                <li class="page-item disabled">
                    <a class="page-link" href="#">Next</a>
                </li>
            </ul>
            {% endif %}
        </footer>
    </body>
</html>

templates/default_form.html
{% extends 'basic.html' %}

{% block content %}
<div class="text-center row">
    <div class="col-md-4 offset-4 jumbotron">
        <form method="post">
            {% csrf_token %}

            <!-- Generic errors -->
            {% if form.non_field_errors %}
                <div class="alert alert-danger">
                    <ul>
                        {% for error in form.non_field_errors %}
                        <li><em>{{ error }}</em></li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}

            {% for field in form.visible_fields %}
                <p>
                    {{ field.label_tag }}
                    <br>
                    {{ field }}
                </p>

                <!-- Field errors-->
                {% if field.errors %}
                    {% for error in field.errors %}
                        <div class="alert alert-danger">
                            <em>{{ error }}</em>
                        </div>
                    {% endfor %}
                {% endif %}
            {% endfor %}

            <input type="hidden" name="next" value='{{ next }}'>
            {% block form_button %}
            {% endblock form_button %}
        </form>
        {% block after_form %}
        {% endblock after_form %}
    </div>
</div>
{% endblock content %}

templates/implemented.html
{% extends 'basic.html' %}

{% block content %}
<div class="text-center row">
    <div class="col-md-4 offset-4 jumbotron">
        {% block text %}
        {% endblock text %}
        <a href="{% url 'books:index' %}">
            <input class='btn btn-success' type="submit" value="Главная">
        </a>
    </div>
</div>
{% endblock content %}

templates/print_books.html
{% extends 'basic.html' %}

{% block content %}
    {% block main_text %}
    {% endblock main_text %}
    <div class="row offset-md-1">
        {% for book in books %}
            <div class="col-md-3">
                <!-- Image -->
                <a class='text-dark'
                href="{% url 'books:book_detail_info' book.pk %}">
                    <img src="{{ book.image.url }}" alt="{{ book }}" height="180">
                </a>

                <!-- Price -->
                <h4><b>{{ book.price }} ₽</b></h4>

                <!-- Title -->
                <a class='text-dark'
                href="{% url 'books:book_detail_info' book.pk %}">
                    <h5>{{ book }}</h5>
                </a>

                <!-- Author -->
                <h6>
                    {% for author in book.authors.all %}
                    <a class='text-dark' href="{% url 'books:author_info' author.pk %}">
                        <!-- Set comma if author is not last -->
                        {{ author }}</a>{% if author != book.authors.last %},
                    {% endif %}
                    {% endfor %}
                </h6>

                <!-- Publishing house and episode -->
                <h6>
                    <a class='text-dark'
                    href="{% url 'books:publishing_house_info' book.publishing_house.pk %}">
                    {{ book.publishing_house }}</a>{% if book.episode %}: 
                    <a class='text-dark'
                    href="{% url 'books:episode_books' book.episode.pk %}">
                        {{ book.episode }}
                    </a>
                    {% endif %}
                </h6>
            </div>
        {% endfor %}
    </div>
{% endblock content %}    